object Form10: TForm10
  Left = 268
  Top = 141
  Width = 927
  Height = 584
  Caption = 'Form10'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Image1: TImage
    Left = 32
    Top = 8
    Width = 851
    Height = 225
    Picture.Data = {
      07544269746D6170A25C0000424DA25C0000000000003E000000280000005603
      0000DB0000000100010000000000645C0000232E0000232E0000020000000000
      000000000000FFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFF
      FFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF
      FFFCFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFF
      FFFFFFF8FFFFFFFFFFF7FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFDFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FE000FFFFFFFFFFFFFFFFFFFF9FFFFF0FFFFFFFFFFE3FFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFF9FFFFFF8FFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC3C1FFFFFFFFFFFFFFFFFFFF9FFFFFCFFFFFFFF
      FFE7FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFCFFFFFF8FFFFFFFFFF9FFFFFFFFFFFFFFFFFFF83E1FFFFFFFFFFF
      FFFFFFFFF9FFFFFC7FFFFFFFFFE7FFFFCFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFCFFFFFFFFFF1FFFFFFFFFF
      FFFFFFFFF87E1FFFFFFFFFFFFFFFFFFFF9FFFFFC7FFFFFFFFFE3FFF80FFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFDFFFF
      FFCFFFFFFFFFF9FFFE01FFFFFFFFFFFFF87F3FFFFFFFFFFFFFFFFFFFF1FFFFFE
      7FFFFFFFFFE7FFE00FFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFCFFFFFFC7FFFFFFFFF9FFF800FFFFFFFFFFFFFC7F1FFF
      FFFFFFFFFFF80067F1FFFFFE7FFFFFFFFFE3F80007FFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFEFFFFDFFFFFFC7FFFFFFFFF8FF
      0000FFFFFFFFFFFFFC3F1FFFFFFFFFFFFFF00000E1FFFFFE3FFFFFFFFFE1C000
      03FFFF80FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFF83
      3FF8FFFFFFC7FFFFFFFFF87C0180FFFFFFFFFF9FFE1F1FFFC07FFFFDE3F00000
      01FFFFFF3FFFFFFFFFE00000000400007C00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFF000000FFFFFFE7FFFFFFFFF800018000000000000F
      FE1F0FFF800008000000000001FFFFFF1FFFFFFFFFE00000000000007C00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFF1FFE000000FFFFFFE3FFFF
      FFFFF800010000000000001FFE1F8FFFC00000000000000001FFFFFF9FE7FFFF
      FFE0000001FFFFCFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      F00000000001FFFFFFF1FE7FFFFFF80001007E00FFFFFFFFFF0F8FFFFFFF2FFF
      FFF00000C1FFFFFF8FC7FFFFFFE3FC0007FFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFF00000000001FFFFFFF9FE7FFFFFF87C0301FFFF
      FFFFFFFFFF8F0FFFFFFFFFFFFFF00007F1FFFFFF83C7FFFFFFE3FFB00FFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFE000019FFFF
      FFF07C7FFFFFF8FFE301FFFFFFFFFFFFFF800FFFFFFFFFFFFFF800FFF0FFFFFF
      800FFFFFFFF7FFFE3FFF9FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFF80CFFCFFFFFFF8007FFFFFF9FFFF21FFFFFFFFFFFFFFC00FFF
      FFFFFFFFFFF80FFFF8FFFFFFC01FFFFFFFE7FFFFFFFF3FFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFF81FFFCFFFFFFF800FFFFFFF9FF
      FFFFFFFFFFFFFFFFFFE007FFFFFFFFFFFFFFFFFFF8FFFFFFF83FFFFFFFF3FFFF
      FFFF3FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFCF
      FFFCFFFFFFFC3FFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFF
      F8FFFFFFFFFFFFFFFFE3FFFFFFFF3FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFF
      FFFFE3FFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFFF3FFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
      FFFFF9FFFFFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFF
      FFE3FFFFFFFF3FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFF
      FFFFFFFFF9FFFFFFFFFFFFFFFFE3FFFFFFFF3FFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFF
      FFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFFFBFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFF
      FFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF8FFFFFF
      FFFFFFFFFFE3FFFFFFFFBFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFBFF
      FFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFFF3FFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF8FF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFE3FFFF
      FFFF3FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF
      FFFCFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      F8FFFFFFFFFFFFFFFFE3FFFFFFFE1FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFF807FFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
      FFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFF
      FFE7FFFFFFF007FFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFF8FFFFFFFFFFFFFFFFE7FFFFFFF007FFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE7FFFFFFE007FF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFF
      FFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFF
      FFFFFFFFFFE7FFFFFFF007FFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFF807FFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF8FF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE7FFFF
      FFF807FFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF
      FFFCFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      F8FFFFFFFFFFFFFFFFE3FFFFFFFC0FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFFC0FFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
      FFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFF
      FFE3FFFFFFFC0FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFFC0FFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFFC0FFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFF
      FFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF8FFFFFF
      FFFFFFFFFFE3FFFFFFFC0FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFF8FFFF
      FFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFE3FFFFFFFC1FFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF8FF
      FFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFF
      FFFE1FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFF
      FFFCFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFF
      F8FFFFFFFFFFFFFFFFE3FFFFFFFE1FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFF
      FFF9FFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFFF1FFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFF
      FFFFFCFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFF
      FFF3FFFFFFFF1FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFC7FFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
      FFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFFF1FFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFCFFFFFFFFFF
      FFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFE3FFFFFFFE1FFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFF
      FFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF8FFFF8FFFBFFFFFFFFFFFF0FFFFFF
      FC7E00000001C00000000003FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFFFFF010000000000000F07FDF
      07FF1FFFFFC07FFFE0FDF3CF800000000000000000000003FC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFE07F
      E0000000000000000000000000000000000000000078000000001E0014000000
      03FFFFE7FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF
      FFFCFFFFFFFFFFFFFF83001FE000000000000000000000000000000000000000
      000000007FFFFFFFFFE1FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFF0001840000000000000000
      00000000000000000000400000000001FFFFFFFFFFE3FFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
      800000441FC7FEFFFFFFFFF7FFB0FD0F0000F8F800000001F0000003FFFFFFFF
      FFF3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFCFFFFFFFFFFFC0000007FFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFF
      FFFFFFFFF0000003FFFFFFFFFFE3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFF00000017FFFFFFFFF
      FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF0000003FFFFFFFFFFE3FFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFF
      FFFFFF80000001FFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF0000001
      FFFFFFFFFFE3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFCFFFFFFFFFF000000007FFFFFFFFFFFFFFFFFFFFCFFFF
      FFFFFFFFFFFFFFFFF80000003FFFFFFFFFE3FFFFFFFFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFC000000007F
      FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF000800007FFFFFFFFF3FFFF
      FFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF
      FFFEFFFFFFFFF0000000007FFFFFFF9FFFF0F7FFFFF0FFFFFFFE3FFFFFFFFFFF
      F003800003FFFFFFFFF3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFC00000000C000000000000000000
      00000000000000000000000000020400003FFFFFFFF3FFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFFFFFF0000
      00000000000000000000000000000000000000000000000000000000003FFFFF
      FFF3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFE7FFFFFFE00000000000000000000000000000000000000000000
      00000FFFFC200000001FFFFFFFE3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFFFFFC0000000000030000000F
      838180003FF007FFFFFE898711847FFFFC0000000003FFFFFFE3FFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFF
      FFF800000000007FFFFFFFFFFFFFFFFFFFF87FFFFFFFFFFFFFFFFFFFFC000000
      0003FFFFFFE3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFE7FFFFFE00000001E007FFFFFFFFFFFFFFFFFFFF8FFFF
      FFFFFFFFFFFFFFFFFC1E00000001FFFFFFE3FFFFFFFFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFFFFC0000001FFFC7F
      FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFF80000003FFFFFE3FFFF
      FFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF
      FFFE7FFFFF8000007FFFFCFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFF
      FCFFFE0000003FFFFFE3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFC7FFFFF0000007FFFFCFFFFFFFFFFFFFFFFFF
      FFFCFFFFFFFFFFFFFFFFFFFFFCFFFFE000003FFFFFE3FFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFFFE000000
      FFFFFCFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFCFFFFF800000FFF
      FFE3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFE7FFFFC000007FFFFFCFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFF
      FFFFFFFFFCFFFFFE000007FFFFE3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFFF800000FFFFFFCFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFFFFFF800003FFFFE3FFFFFFFFFF9F
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFF
      F000007FFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFFFFFF
      C00001FFFFE3FFFFFFFFFE0FFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFE7FFFE00003FFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFF1FFFFFFF00000FFFFF3FFFFFFFFF80FFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE7FFF800003FFFFFFFCFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFC00007FFFE3FFFF
      FFFFE0FFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFF
      FFFE7FFF000007FFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      F1FFFFFFFE00001FFFE3FFFFFFFC01FFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFF00000FFFFFFFF8FFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFF00000FFFE3FFFFFFF007FFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE7FFF00000FFF
      FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFC0000F
      FFE3FFFFFF807FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFF
      FFFFFFFFFFFE7FFE00000FFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFF1FFFFFFFFC00007FFE3FFFFFF00FFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE7FFC00000FFFFFFFFCFFFFFFFFFF
      FFFFFFFFFFFDFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFE00007FFE3FFFFFF83FFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFC7FFC
      00000FFFFFFFFCFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF1FFFFFF
      FFE00003FFE3FFFFFF87FFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFF
      FFFFFFFFFFFFFFFFFFFC7FF800000FFFFFFFFCFFFFFFFFFFFFFFFFFFFFF8FFFF
      FFFFFFFFFFFFFFFFF1FFFFFFFFF00000FFE3FFFFFFC7FFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE7FF000000FFFFFFFFCFF
      FFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF1FFFFFFFFF000007FE3FFFF
      FFC7FFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF
      FFFE7FF0000003FFFFFFFCFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFF
      F1FFFFFFFFE000007FE3FFFFFF87FFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF1FFFFFFFFFFFFFFFFFFFFFFE7FF0000701FFFFFFFCFFFFFFFFFFFFFFFFFF
      FFF8FFFFFFFFFFFFFFFFFFFFF1FFFFFFFF8000007FE3FFFFFF87FFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE7FE0000F80FF
      FFFFFCFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF1FFFFFFFE000000
      3FE3FFFFFF80FFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFF
      FFFFFFFFFFFE7FC0001FC01FFFFFFC7FFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFF
      FFFFFFFFF1FFFFFFF807C0003FF3FFFFFF807FFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE7F80007FE00FFFFFFC7FFFFFFFFF
      FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF1FFFFFFF00FC0001FE3FFFFFF807FFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE7F80
      007FF007FFFFFC7FFFFFFFFFFFFFFFFFFFFDFFFFFFFFFFFFFFFFFFFFF1FFFFFF
      E00FE0001FE3FFFFFFC07FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFE3F80007FF001FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFF1FFFFFF800FE0001FE3FFFFFFFFFFFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE3F0000FFF0007FFFFCFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFF001FF0000FE3FFFF
      FFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF
      FFFE3F0000FFF8007FFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      F0FFFFFC003FF00007E3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF1FFFFFFFFFFFFFFFFFFFFFFE3E0000FFFE007FFFFCFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFC007FF00007F3FFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFE0FFFFFFFFFFFFFFFFFFFFFFFFFE0FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE3F0007FFFE00
      7FFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFF000FFF800
      03E3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFC013FFFFFFFFFFF9
      FFFFFFF8FFF807FFFFFFFFFFFFFFFFFFDFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFF
      FFFFFFFFFFFE3E0007FFFE003FFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFF1FFFFE000FFFC0003F3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFF8001FFFFFFFFFFF1FFFFFFF83FF007FFFFFFFFFFFFFFFFFF87FFFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE3C0007FFFE007FFFFCFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFC001FFFC0003F3FFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF0001FFFFFFFFFFF1FFFFFFF81FF007FF
      FFFFFFFFFFFFFFFF87FFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFE3800
      0FFFFE003FFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFC0
      03FFFC0003F3FFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF03F1FFFF
      FFFFFFE1FFFFFFF80FF807FFFFFFFFFFFFFFFFFF87FFFFFFFFFFFFFFFFFC1FFF
      FFFFFFFFFFFFFFFFFFFE38000FFFFF003FFFFCFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFF0FFFFC007FFFE0003F3FFFFFFFFFFFFFC00FF03F8FE07E0
      0FF07FFCFCFFFFFF83F0FFFFFFFFFFC3FFFFFFF80FFE0FFFFFFFFFFFFFFFFFFF
      83FFFFFFFFFFFFFFFFFC1FFFFFFFFFFFFFFFFFFFFFFE00001FFFFF803FFFFCFF
      FFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF0FFFFC00FFFFE0001F3FFFF
      FFFFFFFFFC00FF03F07807E00F807FF87C3FFFFFC0007E03FFFFFF83FF1FCFF8
      07FE063FFE0CFFCFFF87E3F3C0FFFFFFFFFFFFFFFFFC1FFFFFFFFFFFFFFFFFFF
      FFFE00009FFFFFFE0FFFFCFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFF
      F0FFFFC00FFFFE0000F3FFFFFFFFFFFFFC00FF07C0F001F00F001FF87C1FE007
      C0007800FFFFFF0FFF1FCFFD07FE003FF800700FE001E1E3F0FFFFFFFFFFFFFF
      FFFE1FFFFFFFFFFFFFFFFFFFFFFE00009FFFFFFF07FFFCFFFFFFFFFFFFFFFFFF
      FFF8FFFFFFFFFFFFFFFFFFFFF0FFFFC00FFFFF0000F3FFFFFFFFFFFFFC00FF07
      C06001F03E000FF87C3FE007C001F800FFFFFF1FFE0F8FFF87FE001FF0000007
      00000003F87FFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE00001FFFFFFF
      C3FFFE7FFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF1FFFFC00FFFFF00
      00F3FFFFFFFFFFFFFC00FF0781C3F8F83C1F87F0383FC003C007F1FC7FFFFE1F
      FE0F8FFF83FE0383F000000600000003F87FFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFE00003FFFFFFFC1FFFCFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFF
      FFFFFFFFF1FFFF801FFFFF800003FFFFFFFFFFFFFC00FF8007C3F8FC3C3F87F8
      001FC063E00FF1FE7FFFFE3FFE078FFF83FE0FC3F0E07C060F830003FC7FFFFF
      FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE00007FFFFFFFE0FFFCFFFFFFFFFF
      FFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF1FFFF0FFFFFFF800003FFFFFFFFFFFF
      FC00FF800FC3F8FC3C3F87F0001FC3FFE00FE1FE7FFFFC3FFC0387FF83FE0FE1
      F3F8FE000F878703FC3FFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE0000
      7FFFFFFFF07FFC7FFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF0FFFE1F
      FFFFFFC00003FFFFFFFFFFFFFC00FF803FC3F8F83C7F87C0001F87FFF00FF3FE
      7FFFFE3FFC0007FF03FE1FE1E3FCFE007F8787C3FC3FFFFFFFFFFFFFFFFF1FFF
      FFFFFFFFFFFFFFFFFFFE00007FFFFFFFF83FFC7FFFFFFFFFFFFFFFFFFFFCFFFF
      FFFFFFFFFFFFFFFFF8FFF07FFFFFFFC00003FFFFFFFFFFFFFC00FF807FC7F8F0
      3C3F87C3C18F87FFF1E3F3FE3FFFFE3FFC0003FF01FE3FF1E3FCFE01FF8FE383
      FE1FFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE00007FFFFFFFFC3FFCFF
      FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF0FFF0FFFFFFFFC00003FFFF
      FFFFFFFFFC00FF807FC7F8E03C7FC7C7C3C787FFC3E3E3FE7FFFFE3FFC7033FF
      1CFE3FE1E3F8FE01FF07E007FE1FFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF
      FFFE00007FFFFFFFFE1FFC7FFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFF
      F1FFE1FFFFFFFFE00003FFFFFFFFFFFFFC00FF807FC7F8F03C3F87C7E3E3C003
      C3E3F3FE7FFFFE3FF87879FE1E7E3FE1F3F8FE03FF07E007FF1FFFFFFFFFFFFF
      FFFF1FFFFFFFFFFFFFFFFFFFFFFE0000FFFFFFFFFF8FFC7FFFFFFFFFFFFFFFFF
      FFFC7FFFFFFFFFFFFFFFFFFFF8FFC3FFFFFFFFF00003FFFFFFFFFFFFFC00FF80
      7FC7F8F83C3F8F8FE3F3C001C3E1E1FE7FFFFE3FE0F879FE3E7E1FE1F3FCFE03
      FF07E207FF1FFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFE0000FFFFFFFF
      FFC7FC7FFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFF07F83FFFFFFFFF0
      0003FFFFFFFFFFFFFC00FF800FC3F1FC3C3F0F0FC3F1C001C3E1F1FC7FFFFE3F
      E0F879FE3E3E1FC3F3FCFE01FF07E787FE1FFFFFFFFFFFFFFFFE1FFFFFFFFFFF
      FFFFFFFFFFFE0000FFFFFFFFFFC3FCFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
      FFFFFFFFF07F0FFFFFFFFFF00007FFFFFFFFFFFFFC00FF8007C1E1FC1E1C0F03
      83E1C003C3E039F07FFFFC3FE0F878783E3E0FC3F3F8FE00FF07C7C7FE3FFFFF
      FFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFE0000FFFFFFFFFFE07CFFFFFFFFFF
      FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF0FF1FFFFFFFFFF0000FFFFFFFFFFFFF
      FC00FF8001F003FC0F001E030081C003E00038E07FFFFE3FC0E038303E1E0707
      C1F0FE007F87C787FC3FFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFE0000
      FFFFFFFFFFF87CFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF1FE3FFF
      FFFFFFF0000FFFFFFFFFFFFFFC00FFC001F003FC1F803F038080E007F0003800
      7FFFFE0FC0C030001C00000F81E0FE000F81C007FC3FFFFFFFFFFFFFFFFE1FFF
      FFFFFFFFFFFFFFFFFFFE0000FFFFFFFFFFFC3E7FFFFFFFFFFFFFFFFFFFFCFFFF
      FFFFFFFFFFFFFFFFF8FC7FFFFFFFFFF00007FFFFFFFFFFFFFC00FFC7F1FE07FC
      1FFFFFFFFFF9F807F8133C03FFFFFE0FC0E030001C00000F81C0FC000F80E007
      FC3FFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFC3E7F
      FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF9F8FFFFFFFFFFF00007FFFF
      FFFFFFFFFC00FF87FFFFFFFC3FFFFFFFFFFFFF03FF3FFF1FFFFFFE0FC5F33C30
      1C03801F81E0FE000F80F01FFC7FFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFF
      FFFE0000FFFFFFFFFFFF1EFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF
      F8F9FFFFFFFFFFF00007FFFFFFFFFFFFFC00FF87FFFFFFFC3FFFFFFFFFFFFFF3
      FFFFFFFFFFFFFF0FFFFFFFFC3E1FFEFFEFFFFE1FFF87FFFFFC7FFFFFFFFFFFFF
      FFFE3FFFFFFFFFFFFFFFFFFFFFFE0000FFFFFFFFFFFF8CFFFFFFFFFFFFFFFFFF
      FFFCFFFFFFFFFFFFFFFFFFFFF8F3FFFFFFFFFFF00007FFFFFFFFFFFFFC00FF0F
      FFFFFFF83FFFFFFFFFFFFFFFFFFFFFFFFFFFFF87FFFFFFFFFFFFFFFFFFFFFE1F
      FF87FFFFF87FFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFE0000FFFFFFFF
      FFFFC0FFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF803FFFFFFFFFFE0
      0007FFFFFFFFFFFFFC00FF0FFFFFFFE03FFFFFFFFFFFFFFFFFFFFFFFFFFFFF83
      FFFFFFFFFFFFFFFFFFFFFC1FFF87FFFFF07FFFFFFFFFFFFFFFFE3FFFFFFFFFFF
      FFFFFFFFFFFF0000FFFFFFFFFFFFE0FFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
      FFFFFFFFF003FFFFFFFFFFC00007FFFFFFFFFFFFFC00FE0FFFFFFFE01FFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFC1FFFFFFFFFFFFFFFFFFFFFC1FFF07FFFFE0FFFFFF
      FFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFE0000FFFFFFFFFFFFE0FFFFFC0000
      3FFFC78061A07FFFFE7FFFFFFFFFFFFF8000F1C0000000000007FFFFFFFFFFFF
      FC00FE07FFFFFFF03FFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0FFFFFFFFFFFFFFFF
      FFFFF81FFF07FFFFC3FFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFE0000
      7DFFFFFBFFFFC07FF3F000001FFF030000000000000000000000000000000000
      000000000001C01E01FC0E01FC00FE07FFFFFFF83FFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFE0FFFFFFFFFFFFFFFFFFFFF01FFE0FFFFF83FFFFFFFFFFFFFFFFFF3FFF
      FFFFFFFFFFFFFFFFFFFE00000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000001FC00FF87FFFFFFFE
      7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFF01FFE07FFFF
      87FFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFE00000000000000000000
      0000000000000000000000000000000000000000000000000000000100000000
      00000003FC00FFCFFFFFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFF01FFE07FFFF8FFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF
      FFFE000000000000000000000000000000000000000000000000000000000000
      000000000000000787E00F3CC07001C3FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFC7FFFFFFFFFFFFFFFFFFFF
      FFFF1FFFFFFFFFFFFFFFFFFFFFFE0FFFFF000BF8000631C001C36FFFF398003F
      C7E03FFFCFF01FE3FFFFFFFFFFFFFFF9DFDFFEFFFFFFFFFFF3FE07FFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFE0FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0FFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0FFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFC0FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0FFFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFC0FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFC0FFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFC1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC07FFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFC07FFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC03FFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC07FF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFC03FFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFF87FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF803FFFC00FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE03FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFF803FFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC03FFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFF803FFFC00FFFFFFFFFF1FFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFF803FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF803FFFC00FFFF
      FFFFFE1FCFFBFFFFFFFFFFFFFFFFFBF3FFFFFFF07FFFFFFFFFFFFFFFFFE7FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFF803FFFC00FFFC0003FE1FCFE00E000C01FF0601FFF1E1FFFFFFF8
      3FFF7FFFFFFFFFFFFF03FFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF803FFFC00FFFC0000FE1F87E00C00
      0C01FE0001E0E003FFFFFFFC01FE01FFFFC7FF07FE01F03FFFFC03007C3E707F
      FFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF803FF
      FC00FFF80000FE1F87F01C000C00FC0001E0E003FFFFFFFC00FE01FC3F007E01
      FE00E00FC0F800000038003FFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFC07FFFC00FFE03FE0FE0F07FC7C181E01FC1C03C00003
      FFFFFFF8307E03F806003E007C00000F807800000000003FFFFFFFFFFFFE3FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFC00FFE0FFF0FC0F
      07FC7E3C1F87FE3F87078381FFFFFFF83E1F07E000007E00703C001E003E0F81
      E000007FFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF8FFFFC00FFC0FFF8FC0707FC7E3C3F8FFE3F870FC783FFFFFFF87E0F8FC0
      01C1FE38F0FE7C7E001F1FC3F1E0007FFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFC00FFC1FFFCFC0007FC7E0C3F8FFE3F
      821FE783FFFFFFF87F0FCF81F1E1FE7CF0FFFC7C0F1F1FC3F1F1C0FFFFFFFFFF
      FFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFC00FFC3
      FFFFF87003FE3E003F8FFE3F803FF3C3FFFFFFF8FF0FCF83FFE3FE78F1FFFE3C
      3FFF1FE7F1F1E1FFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF9FFFFC00FF83FFFFF8F831FE7F003F8FFE3F807FF007FFFFFFF8
      FF8FC787FFE3FF80F1FFFC3C7FFF1FE7F3F001FFFFFFFFFFFFFE3FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFC00FF83FFFFF0F879FC7E38
      3F8FFE3F807FF007FFFFFFF8FF8FCF87FFE3FF00F1FFFC387FFF1FC7F3F801FF
      FFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFF
      FC00FF03FFFFF0F879FC7E7C3F8FFE3F80FFE707FFFFFFF8FF8FCF87FFE3FF01
      F1FFFC3C7FFF1FC7F1F801FFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF9FFFFC00FF03FFFFE1F878FC7C3C3F87FE3F803FE787
      FFFFFFF07F0FC783F3E3FE01F1FFFC3C7FFF1FC7E3F1C1FFFFFFFFFFFFFE1FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFC00FF83FFFFC0F0
      78F87C7C3F07FC3F803FE787FFFFFFF07E1FC78003E3FE01F1FC7C7C001F1FC7
      E3F1C1FFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFF8FFFFC00FF87FFFFC0C030007E003E003C3F831FE307FFFFFFF03E1F8F80
      03E1F838F8F8787C001E1F87E3F1E1FFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFC00FF87FFFFC08010007F003C00000F
      8203E007FFFFFFE0001F078003C00078F800607E001C0E07C1F1E0FFFFFFFFFF
      FFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFC00FF83
      FFFCC1C0303C7F007C0000078003E007FFFFFFC0001E078003800078F800007E
      00180007C1F1C1FFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFF8FFFFC00FFC3FFF87FFFFFFFFFFFFF00100F83E1F81FFFFFFFC0
      007F0FC003000001FC00E07E007C000FC1F803FFFFFFFFFFFFFE1FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFC00FFE1FFF0FFFFFFFFFFFF
      FFDFFE3F87E7FFFFFFFFFFFFFFFFFFF81FC00783FFFFFE7F00FE181FF3FC07FF
      FFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FC00FFE0FFF0FFFFFFFFFFFFFFFFFE3F87FFFFFFFFFFFFFFFFFFFFFC1FE00FC3
      FFFFFE7F00FF3C3FF3FFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC00FFE03FE0FFFFFFFC3FFFFFFFFF7F87FFFFFF
      FFFFFFFFFFFFFFFE3FFFFFC7FFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFE3FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFF01F80FFFF
      FFFC3FFFFFFFFFFF07FFFFFFFFFFFFFFFFFFC7FFFFFFFFE7FFFFFF3FFFFFFFFF
      FFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFC00FFF80000FFFFFFFC3FFFFFFFFFFE07FFFFFFFFFFFFFFFFFFC7FF
      FFFFFFE3FFFFFE3FFFFFFFFFF1FFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFF0003FFFFFFFC3FFFFFFFFFFC
      07FFFFFFFFFFFFFFFFFF87FFFFFFFFC0FFFFF83FFFFFFFFFE07FFFFFFFFFFFFF
      FFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFF
      801FFFFFFFFC7FFFFFFFFFFC03FFFFFFFFFFFFFFFFFF87FFFFFFFFC0FFFFF03F
      FFFFFFFFE07FFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFC00FFFFF87FFFFFFFFFFFFFFFFFFFFE07FFFFFFFFFFFFFF
      FFFF87FFFFFFFFE0FFFFF03FFFFFFFFFE0FFFFFFFFFFFFFFFFFE1FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFF87FFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFE3FFFFFC7FFFFFFFFFF1FFFFFF
      FFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FC00FFFFF83FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFF81FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFC1FFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFC00FFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFC00}
  end
  object d: TLabel
    Left = 408
    Top = 264
    Width = 9
    Height = 20
    Caption = 'd'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label1: TLabel
    Left = 320
    Top = 392
    Width = 100
    Height = 20
    Caption = 'Powierzchnia'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Label2: TLabel
    Left = 408
    Top = 304
    Width = 6
    Height = 20
    Caption = 'r'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
  end
  object Edit1: TEdit
    Left = 424
    Top = 264
    Width = 153
    Height = 21
    TabOrder = 0
    Text = '0'
    OnChange = Edit1Change
  end
  object Edit2: TEdit
    Left = 424
    Top = 304
    Width = 153
    Height = 21
    TabOrder = 1
    Text = '0'
    OnChange = Edit2Change
  end
  object Memo1: TMemo
    Left = 424
    Top = 384
    Width = 169
    Height = 33
    Lines.Strings = (
      'Memo1')
    TabOrder = 2
  end
  object Button1: TButton
    Left = 400
    Top = 448
    Width = 201
    Height = 65
    Caption = 'Licz'
    TabOrder = 3
    OnClick = Button1Click
  end
  object Button2: TButton
    Left = 720
    Top = 472
    Width = 177
    Height = 57
    Caption = 'Zamknij'
    TabOrder = 4
    OnClick = Button2Click
  end
end
